export { ReactComponent as LogoImage } from './logo.svg';
export { ReactComponent as Comment } from './icon-writing-box-paper.svg';
export { ReactComponent as Document } from './icon-ai-powered.svg';
export { ReactComponent as ArrowRight } from './arrow-right.svg';
export { ReactComponent as ArrowDown } from './arrow-down.svg';
export { ReactComponent as Favourite } from './favourite.svg';
export { ReactComponent as User } from './user.svg';
export { ReactComponent as Hamburger } from './hamburger.svg';
export { ReactComponent as Close } from './close.svg';
