name: backend CD
on:
  push:
    paths:
      - 'back/**'
      - 'front/**'
    branches: ['master']
  pull_request:
    paths:
      - 'back/**'
      - 'front/**'
    branches: ['master']
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: |
            back:
              - 'back/**'
            front:
              - 'front/**'

      - uses: actions/checkout@v2

      - name: execute remote ssh & deploy backend server
        if: steps.changes.outputs.back == 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          passphrase: ${{ secrets.REMOTE_SSH_PASSPHRASE }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            whoami
            cd ../../usr/KORrection/back
            sudo git pull origin master
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            yarn install
            pm2 restart back-server

      - name: execute remote ssh & deploy frontend server
        if: steps.changes.outputs.front == 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          passphrase: ${{ secrets.REMOTE_SSH_PASSPHRASE }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            whoami
            cd ../../usr/KORrection/front
            sudo git pull origin master
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            yarn install
            yarn build
            sudo systemctl reload nginx
